package edu.jabs.imageViewer.interfaz;

import java.awt.*;
import java.awt.event.*;

import javax.swing.*;

/**
 * Convolution array buttons pane
 */
public class ArrayButtonsPane extends JPanel implements ActionListener
{
    //-----------------------------------------------------------------
    // Constants
    //-----------------------------------------------------------------

    /**
     * Accept
     */
    public final static String ACCEPT = "accept";

    /**
     * Clean
     */
    public final static String CLEAN = "clean";

    /**
     * Cancel
     */
    public final static String CANCEL = "cancel";

    //-----------------------------------------------------------------
    // GUI Fields
    //-----------------------------------------------------------------

    /**
     * Accept button
     */
    private JButton butAccept;

    /**
     * Clean Button
     */
    private JButton butClean;

    /**
     * Cancel button
     */
    private JButton butCancel;

    //-----------------------------------------------------------------
    // Fields
    //-----------------------------------------------------------------

    /**
     * Dialogue that owns this panel
     */
    private ConvolutionArrayDialogue dialogue;

    //-----------------------------------------------------------------
    // Constructors
    //-----------------------------------------------------------------

    /**
     * It builds the convolution matrix buttons pane
     * @param theDialogue Dialogue that owns this panel. theDialogue != null.
     */
    public ArrayButtonsPane( ConvolutionArrayDialogue theDialogue )
    {
        //The parent reference is saved
        dialogue = theDialogue;

        //The layout is set
        setLayout( new GridLayout( 1, 3 ) );

        //The graphical elements are initilized
        butAccept = new JButton( "Accept" );
        butAccept.setActionCommand( ACCEPT );
        butAccept.addActionListener( this );

        butClean = new JButton( "Clean" );
        butClean.setActionCommand( CLEAN );
        butClean.addActionListener( this );

        butCancel = new JButton( "Cancel" );
        butCancel.setActionCommand( CANCEL );
        butCancel.addActionListener( this );

        //The elements are added to the pane
        add( butAccept );
        add( butClean );
        add( butCancel );
    }

    //-----------------------------------------------------------------
    // Methods
    //-----------------------------------------------------------------

    /**
     * It executes the action events
     * @param event Event generated by an action. event != null.
     */
    public void actionPerformed( ActionEvent event )
    {
        String command = event.getActionCommand( );
        if( command.equals( ACCEPT ) )
        {
            dialogue.accept( );
        }
        if( command.equals( CLEAN ) )
        {
            dialogue.clean( );
        }
        if( command.equals( CANCEL ) )
        {
            dialogue.cancel( );
        }
    }
}